language:
  - cpp

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libncursesw5-dev
      - libtag1-dev
      - qt5-default
      - qt5-qmake
      - qtmultimedia5-dev
      - libqt5multimedia5-plugins

install:
  - if [ $TRAVIS_OS_NAME = osx ]; then
      brew update;
      brew install ncurses taglib qt5;
      brew link --force qt;
    fi

script:
  - qmake
  - make -s
