language:
  - cpp

sudo:
  - required

os:
  - linux
  - osx

install:
  - echo $TRAVIS_OS_NAME
  - if [ $TRAVIS_OS_NAME = linux ]; then
      sudo apt update;
      sudo apt -y install libncursesw5-dev libtag1-dev qt5-default qt5-qmake
               qtmultimedia5-dev libqt5multimedia5-plugins;
    fi

script:
  - qmake
  - make -s

