name: Linux

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - dev/*

jobs:
  linux-build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build Linux
      run: ./make.sh all
